In [32]:
'''
로지스틱 회귀분석 - Binary
'''

'\n로지스틱 회귀분석 - Binary\n'

In [33]:
import numpy as np
import pandas as pd 
from sklearn.datasets import load_breast_cancer

raw = load_breast_cancer()
raw_df = pd.DataFrame(raw.data, columns=raw.feature_names)
raw_df['target'] = raw.target

raw_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [34]:
df = raw_df.copy()

X = df.drop(columns='target').loc[:,]
y = df['target']

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

pca = PCA(n_components=.8)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [36]:
import statsmodels.api as sm

# df = raw_df.copy()

# X = df.drop(columns='target').loc[:,]
# y = df['target']

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )
X_const_train = sm.add_constant(X_train)

model = sm.Logit(y_train, X_const_train)
model_fitted = model.fit()
print(model_fitted.summary())

Optimization terminated successfully.
         Current function value: 0.077781
         Iterations 11
                           Logit Regression Results
==============================================================================
Dep. Variable:                 target   No. Observations:                  455
Model:                          Logit   Df Residuals:                      449
Method:                           MLE   Df Model:                            5
Date:                Sat, 02 Aug 2025   Pseudo R-squ.:                  0.8821
Time:                        19:53:11   Log-Likelihood:                -35.390
converged:                       True   LL-Null:                       -300.17
Covariance Type:            nonrobust   LLR p-value:                3.322e-112
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6630      0.336      1.971      0.049       0.004       1.322
x1            -2.7978      0.449     -6.225      0.000      -3.679      -1.917
x2             1.6021      0.323      4.963      0.000       0.969       2.235
x3             0.5703      0.201      2.841      0.004       0.177       0.964
x4            -0.9820      0.245     -4.008      0.000      -1.462      -0.502
x5            -1.0693      0.399     -2.681      0.007      -1.851      -0.288
==============================================================================

Possibly complete quasi-separation: A fraction 0.42 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [38]:
model_fitted.prsquared

np.float64(0.8820984528514422)

In [ ]:
odds_ratios = pd.DataFrame({
    'OR': result.params.apply(lambda x: round(np.exp(x), 3)),
    '2.5%': result.conf_int()[0].apply(lambda x: round(np.exp(x), 3)),
    '97.5%': result.conf_int()[1].apply(lambda x: round(np.exp(x), 3))
})
display(odds_ratios)
print(
'''
x1 -> 1 증가할 때 1일 확률이 0.061배 증가
x2 -> 1 증가할 때 1일 확률이 4.963배 증가
x3 -> 1 증가할 때 1일 확률이 1.769배 증가
x4 -> 1 증가할 때 1일 확률이 0.375배 증가
x5 -> 1 증가할 때 1일 확률이 0.343배 증가
'''
)

       Odds_Ratio   2.5%  97.5%
const       1.941  1.004  3.751
x1          0.061  0.025  0.147
x2          4.963  2.636  9.344
x3          1.769  1.194  2.621
x4          0.375  0.232  0.605
x5          0.343  0.157  0.750

In [ ]:
import seaborn as sns

raw_df = sns.load_dataset('penguins')
raw_df = raw_df.dropna()
raw_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [ ]:
import statsmodels.formula.api as smf

df = raw_df.copy()
df = df.dropna()
target_col = 'sex'
df[target_col] = (df[target_col] == 'Male').astype(int)

formula = 'sex ~ C(species) + C(island)'
model = smf.logit(formula, data=df)
results = model.fit()
print(results.summary())

Optimization terminated successfully.
         Current function value: 0.692974
         Iterations 3
                           Logit Regression Results
==============================================================================
Dep. Variable:                    sex   No. Observations:                  333
Model:                          Logit   Df Residuals:                      328
Method:                           MLE   Df Model:                            4
Date:                Thu, 24 Apr 2025   Pseudo R-squ.:               0.0001908
Time:                        19:29:13   Log-Likelihood:                -230.76
converged:                       True   LL-Null:                       -230.80
Covariance Type:            nonrobust   LLR p-value:                    0.9991
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                9.171e-18      0.302   3.04e-17      1.000      -0.591       0.591
C(species)[T.Chinstrap]    -0.0364      0.363     -0.100      0.920      -0.747       0.675
C(species)[T.Gentoo]        0.0504      0.353      0.143      0.886      -0.641       0.742
C(island)[T.Dream]          0.0364      0.405      0.090      0.928      -0.757       0.829
C(island)[T.Torgersen]     -0.0426      0.420     -0.101      0.919      -0.865       0.780
===========================================================================================

In [ ]:
import pandas as pd
import statsmodels.api as sm

df = raw_df.copy()
df = df.dropna()
target_col = 'sex'
df[target_col] = (df[target_col] == 'Male').astype(int)


_df = df.loc[:, ['species', 'island', 'sex']]
_df = pd.get_dummies(_df, columns=['species', 'island'], dtype=int, drop_first=True)

X = _df.drop(columns=[target_col])
y = _df[target_col]

In [ ]:
X_const = sm.add_constant(X)
model = sm.Logit(y, X_const)
results = model.fit()
print(results.summary())

Optimization terminated successfully.
         Current function value: 0.692974
         Iterations 3
                           Logit Regression Results
==============================================================================
Dep. Variable:                    sex   No. Observations:                  333
Model:                          Logit   Df Residuals:                      328
Method:                           MLE   Df Model:                            4
Date:                Thu, 24 Apr 2025   Pseudo R-squ.:               0.0001908
Time:                        19:29:16   Log-Likelihood:                -230.76
converged:                       True   LL-Null:                       -230.80
Covariance Type:            nonrobust   LLR p-value:                    0.9991
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const             -4.046e-16      0.302  -1.34e-15      1.000      -0.591       0.591
species_Chinstrap    -0.0364      0.363     -0.100      0.920      -0.747       0.675
species_Gentoo        0.0504      0.353      0.143      0.886      -0.641       0.742
island_Dream          0.0364      0.405      0.090      0.928      -0.757       0.829
island_Torgersen     -0.0426      0.420     -0.101      0.919      -0.865       0.780
=====================================================================================